news_app/urls.py
from django.urls import path
from .views import ExchangeRateNewsView

urlpatterns = [
    path('news/', ExchangeRateNewsView.as_view(), name='exchange_rate_news'),
]

notes_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('', views.note_home, name='note_home'),
    path('', views.note_list, name='note_list'),
    path('add/', views.add_note, name='add_note'),
    path('edit/<int:note_id>/', views.edit_note, name='edit_note'),
    path('delete/<int:note_id>/', views.delete_note, name='delete_note'),
    path('<int:note_id>/', views.note_detail, name='note_detail'),
    path('add_tag/', views.add_tag, name='add_tag'),
    path('tag_list/', views.tag_list, name='tag_list'),
    path('tag_list/delete/<int:tag_id>/', views.delete_tag, name='delete_tag')
]

personal_assistant/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name='home'),
    path('home/', HomePageView.as_view(), name='home'),
    path('contacts/', include('contacts_app.urls')),
    path('notes/', include('notes_app.urls')),
    path('news/', include('news_app.urls')),
    path('users/', include('users_app.urls')),
    path('files/', include('files_app.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes_app/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Note(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title

notes_app/forms.py
from django import forms
from .models import Note, Tag


class NoteForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple,
        label='Tags'
    )

    class Meta:
        model = Note
        fields = ['title', 'content', 'tags']
        labels = {
            'title': 'Title',
            'content': 'Description',
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(NoteForm, self).__init__(*args, **kwargs)
        if user is not None:

            self.fields['tags'].queryset = Tag.objects.filter(created_by=user)


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'id': 'tagNameInput'})
        }

notes_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.views.decorators.http import require_POST

from django.http import JsonResponse
from .models import Note, Tag
from .forms import NoteForm, TagForm





# @login_required
# def note_home(request):
#     notes = Note.objects.filter(created_by=request.user)
#     return render(request, 'notes_app/note_home.html', {'notes': notes})


@login_required
def add_note(request):
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            note = form.save(commit=False)
            note.created_by = request.user
            note.save()

            tag_ids = request.POST.getlist('tags')
            for tag_id in tag_ids:
                if tag_id:
                    try:
                        tag = Tag.objects.get(
                            id=tag_id, created_by=request.user)
                        note.tags.add(tag)
                    except Tag.DoesNotExist:
                        continue

            new_tag_name = request.POST.get('new_tag')
            if new_tag_name:
                tag, created = Tag.objects.get_or_create(
                    name=new_tag_name.strip(),
                    defaults={'created_by': request.user}
                )
                if created:
                    note.tags.add(tag)

            return redirect('note_list')
    else:
        form = NoteForm()

    user_tags = Tag.objects.filter(created_by=request.user)
    return render(request, 'notes_app/add_note.html', {'form': form, 'tags': user_tags})


@login_required
def note_list(request):
    query = request.GET.get('q')
    tag_query = request.GET.get('tag')
    notes = Note.objects.filter(created_by=request.user).order_by('-created_at')

    if query:
        notes = notes.filter(
            Q(title__icontains=query) | Q(tags__name__icontains=query)
        ).distinct()

    if tag_query:
        notes = notes.filter(tags__name__icontains=tag_query).distinct()

    paginator = Paginator(notes, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'notes_app/note_list.html', {'page_obj': page_obj, 'query': query, 'tag_query': tag_query})


@login_required
def edit_note(request, note_id):
    note = get_object_or_404(Note, id=note_id, created_by=request.user)
    note_tags = note.tags.all()
    if request.method == "POST":
        form = NoteForm(request.POST, instance=note)
        if form.is_valid():
            note = form.save(commit=False)
            note.created_by = request.user
            note.save()

            note.tags.clear()
            
            tag_ids = request.POST.getlist('tags')
            for tag_id in tag_ids:
                if tag_id:
                    try:
                        tag = Tag.objects.get(
                            id=tag_id, created_by=request.user)
                        note.tags.add(tag)
                    except Tag.DoesNotExist:
                        continue

            # Добавляем новый тег, если он был введён
            new_tag_name = request.POST.get('new_tag')
            if new_tag_name:
                tag, created = Tag.objects.get_or_create(
                    name=new_tag_name.strip(),
                    defaults={'created_by': request.user}
                )
                if created:
                    note.tags.add(tag)

            return redirect('note_list')
    else:
        form = NoteForm(instance=note)

    user_tags = Tag.objects.filter(created_by=request.user)

    return render(request, 'notes_app/edit_note.html', {'form': form, 'note': note, 'tags': user_tags, 'note_tags': note_tags})


@login_required
def delete_note(request, note_id):
    note = get_object_or_404(Note, id=note_id, created_by=request.user)
    note.delete()
    return redirect('note_list')


@login_required
def note_list_sorted(request):
    tag = request.GET.get('tag')
    if tag:
        notes = Note.objects.filter(
            tags__name__icontains=tag, created_by=request.user)
    else:
        notes = Note.objects.filter(created_by=request.user)
    return render(request, 'notes_app/note_list.html', {'notes': notes})


@login_required
def note_detail(request, note_id):
    note = get_object_or_404(Note, id=note_id, created_by=request.user)
    return render(request, 'notes_app/note_detail.html', {'note': note})


@login_required
def add_tag(request):
    if request.method == "POST":
        tag_name = request.POST.get('name')
        if tag_name:
            tag, created = Tag.objects.get_or_create(
                name=tag_name.strip(),
                defaults={'created_by': request.user}
            )
            if created:
                messages.success(request, 'Tag added successfully!')
            else:
                messages.warning(request, 'Tag already exists!')
    return redirect(request.META.get('HTTP_REFERER', 'add_note'))

@login_required
def tag_list(request):
    tags = Tag.objects.filter(created_by=request.user).order_by('name')

    paginator = Paginator(tags, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'notes_app/tag_list.html', {'page_obj': page_obj})

    # return render (request, 'notes_app/tag_list.html', {'tags': tags})


# @login_required
# @require_POST
# def add_tag(request):
#     form = TagForm(request.POST)
#     if form.is_valid():
#         tag = form.save(commit=False)
#         tag.created_by = request.user
#         tag.save()
#     if tag:
#         JsonResponse({'success': True, 'tag': tag.name})
#     else:
#         JsonResponse({'success': False, 'errors': form.errors})
#     return redirect(request.META.get('HTTP_REFERER', 'add_note'))

@login_required
def delete_tag(request, tag_id):
    tag = get_object_or_404(Tag, id=tag_id, created_by=request.user)
    tag.delete()
    return redirect('tag_list')

templates/notes_app/add_note.html
{% extends 'base.html' %}

{% block title %}Create note{% endblock %}

{% load notes_custom_filters %}
{% block content %}
<div class="card contact-form-container mt-4 shadow">

    <h1 class="m-2">Create note</h1>


    <div class="card-body">
        {% if messages %}
        <div class="container mt-3">
            {% for message in messages %}
                <div id="success-message" class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
        {% endif %}
        
        <form method="POST" class="p-4 rounded" id="noteForm">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_title">{{ form.title.label }}</label>
                {{ form.title|add_class:"form-control" }}
            </div>
            
            <div class="form-group">
                <label for="id_content">{{ form.content.label }}</label>
                {{ form.content|add_attrs:"form-control,3" }}
            </div>
        
            <div class="form-group">
                <label for="id_tags" class="d-flex align-items-center">
                    Tags:
                    <div id="selected-tags" class="d-flex flex-wrap ms-2"></div> 
                </label>
                <div class="d-flex flex-wrap" id="tag-container">
                    {% for tag in tags %}
                        <div class="me-2 mb-2">
                            <input type="checkbox" class="d-none" id="tag{{ tag.id }}" name="tags" value="{{ tag.id }}" onchange="updateTagStyle(this)">
                            <label class="btn btn-outline-secondary tag-label" for="tag{{ tag.id }}" style="background-color: #6FBDA2; color: #3D6657; padding: 5px 10px; border-radius: 5px; transition: background-color 0.2s;">
                                {{ tag.name }}
                            </label>
                        </div>
                    {% endfor %}
                </div>
            </div>

            <div class="form-group">
                <label for="newTagName">Add new tag:</label>
                <input type="text" id="newTagName" class="form-control mt-2" placeholder="Enter new tag's name">
                <button type="button" class="btn btn-primary mt-2" id="createTagButton">Create</button>
            </div>
        
            <div class="d-flex justify-content-between">
                <button type="submit" class="btn btn-primary" style="flex: 1; background-color: #097812; margin-right: 10px; padding: 6px 12px; margin-top: 8px;">Save note</button>
                <a href="{% url 'note_list' %}" class="btn btn-block" style="flex: 1; background-color: #3D6657; border-color: #40886E; color: #fff; padding: 6px 12px; margin-top: 8px;">Back to list</a>
            </div>
        </form>

        <form method="POST" action="{% url 'add_tag' %}" id="addTagForm" style="display:none;">
            {% csrf_token %}
            <input type="hidden" name="name" id="hiddenTagName">
        </form>
    </div>
</div>

<script>
    function updateTagStyle(checkbox) {
        const label = document.querySelector(`label[for="${checkbox.id}"]`);
        const selectedTagsContainer = document.getElementById('selected-tags');

        if (checkbox.checked) {
            label.style.backgroundColor = '#3D6657';
            label.style.color = '#E2B29B';

            const badge = document.createElement('span');
            badge.className = 'badge me-2 ml-1';
            badge.textContent = label.textContent;
            badge.style.backgroundColor = '#3D6657';

            selectedTagsContainer.appendChild(badge);
        } else {
            label.style.backgroundColor = '#6FBDA2';
            label.style.color = '#3D6657';

            const badgeToRemove = Array.from(selectedTagsContainer.children).find(badge => badge.textContent === label.textContent);
            if (badgeToRemove) {
                badgeToRemove.remove();
            }
        }
    }

    document.getElementById('createTagButton').addEventListener('click', function(event) {
        event.preventDefault();
        const newTagName = document.getElementById('newTagName').value.trim();
        if (newTagName) {
            const addTagForm = document.getElementById('addTagForm');
            if (addTagForm) {
                document.getElementById('hiddenTagName').value = newTagName;
                addTagForm.submit();
            } else {
                console.error('Форма addTagForm не найдена.');
            }
        }
    });

    document.addEventListener('DOMContentLoaded', function() {
        var successMessage = document.getElementById('success-message');
        if (successMessage) {
            setTimeout(function() {
                successMessage.style.display = 'none';
            }, 3000);
        }
    });
</script>

<style>
    .tag-label:hover {
        background-color: #40886E;
        color: white;
    }
</style>
{% endblock %}

templates/notes_app/add_tag.html
<!-- Кнопка для вызова модального окна -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#tagModal">
    Add Tag
  </button>
  
  <!-- Модальное окно -->
  <div class="modal fade" id="tagModal" tabindex="-1" aria-labelledby="tagModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="tagModalLabel">Add New Tag</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form id="tagForm">
            {% csrf_token %}
            <div class="mb-3">
              <label for="tagName" class="form-label">Tag Name</label>
              <input type="text" class="form-control" id="tagName" name="tagName" required>
            </div>
            <div id="tagFormError" class="alert alert-danger d-none"></div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" id="saveTagBtn">Save Tag</button>
        </div>
      </div>
    </div>
  </div>
  

templates/notes_app/edit_note.html
{% extends 'base.html' %}

{% block title %}Edit note{% endblock %}

{% load notes_custom_filters %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/note_edit.css' %}">

{% block content %}
<div class="card contact-form-container mt-4 shadow">
    <h1 class="m-2">Edit note</h1>
    <div class="card-body">
        {% if messages %}
        <div class="container mt-3">
            {% for message in messages %}
                <div id="success-message" class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
        {% endif %}
        

        
        <form method="POST" class="p-4 rounded">
        {% csrf_token %}
        
            <div class="form-group">
                <label for="id_title">{{ form.title.label }}</label>
                {{ form.title|add_class:"form-control" }}
            </div>
        
            <div class="form-group">
                <label for="id_content">{{ form.content.label }}</label>
                {{ form.content|add_attrs:"form-control,3" }}
            </div>
                


            <div class="form-group">
                <label for="id_tags" class="d-flex align-items-center">
                    Tags:
                    <div id="selected-tags" class="d-flex flex-wrap ms-2">

                    </div>                         
                </label>
                <div class="d-flex flex-wrap" id="tag-container">
                    {% for tag in tags %}
                        <div class="me-2 mb-2">
                            <!-- Проверяем, выбран ли тег -->
                            <input type="checkbox" class="d-none" id="tag{{ tag.id }}" name="tags" value="{{ tag.id }}"
                                    {% if tag in form.instance.tags.all %} checked {% endif %}
                                    onchange="updateTagStyle(this)">
                            <label class="btn btn-outline-secondary tag-label" for="tag{{ tag.id }}" style="background-color: {% if tag in form.instance.tags.all %} #3D6657 {% else %} #6FBDA2 {% endif %}; color: {% if tag in form.instance.tags.all %} #E2B29B {% else %} #3D6657 {% endif %}; padding: 5px 10px; border-radius: 5px; transition: background-color 0.2s;">
                                {{ tag.name }}
                            </label>
                        </div>
                    {% endfor %}
                </div>
            </div>
 
            <div class="form-group">
                <label for="newTagName">Add new tag:</label>
                <input type="text" id="newTagName" class="form-control mt-2" placeholder="Enter new tag name">
                <button type="button" class="btn btn-primary mt-2" id="createTagButton">Create tag</button>
            </div>

            <div class="d-flex justify-content-between">
                <button type="submit" class="btn btn-primary" style="flex: 1; margin-right: 10px; padding: 6px 12px; margin-top: 8px;">Update note and Quit</button>
                <a href="{% url 'delete_note' note.id %}" class="btn" style="flex: 1; margin-right: 10px; padding: 6px 12px; margin-top: 8px; background-color: #a40c0c;" onclick="return confirm('Are you sure you want to delete this note?');">Delete</a>
                <a href="{% url 'note_list' %}" class="btn btn-block" style="flex: 1; background-color: #3D6657; border-color: #40886E; color: #fff; padding: 6px 12px; margin-top: 8px;">Back to list</a>
            </div>
        </form>
    
        <form method="POST" action="{% url 'add_tag' %}" id="addTagForm" style="display:none;">
            {% csrf_token %}
            <input type="hidden" name="name" id="hiddenTagName">
        </form>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
    const selectedTagsContainer = document.getElementById('selected-tags');
    const checkboxes = document.querySelectorAll('input[type="checkbox"][name="tags"]');

    // Инициализация уже выбранных тегов
    checkboxes.forEach(checkbox => {
        if (checkbox.checked) {
            const label = document.querySelector(`label[for="${checkbox.id}"]`);
            // Проверяем, не добавлен ли уже тег
            if (!Array.from(selectedTagsContainer.children).some(badge => badge.textContent === label.textContent)) {
                const badge = document.createElement('span');
                badge.className = 'badge me-2 ml-1';
                badge.textContent = label.textContent;
                badge.style.backgroundColor = '#3D6657';
                badge.style.color = '#E2B29B';
                selectedTagsContainer.appendChild(badge);
            }
        }
    });

    // Функция для обновления стиля тегов при выборе/снятии
    window.updateTagStyle = function(checkbox) {
        const label = document.querySelector(`label[for="${checkbox.id}"]`);

        if (checkbox.checked) {
            label.style.backgroundColor = '#3D6657';
            label.style.color = '#E2B29B';

            // Проверяем, не добавлен ли уже тег
            if (!Array.from(selectedTagsContainer.children).some(badge => badge.textContent === label.textContent)) {
                const badge = document.createElement('span');
                badge.className = 'badge me-2 ml-1';
                badge.textContent = label.textContent;
                badge.style.backgroundColor = '#3D6657';
                badge.style.color = '#E2B29B';
                selectedTagsContainer.appendChild(badge);
            }
        } else {
            label.style.backgroundColor = '#6FBDA2';
            label.style.color = '#3D6657';

            // Удаляем тег из списка выбранных
            const badgeToRemove = Array.from(selectedTagsContainer.children).find(badge => badge.textContent === label.textContent);
            if (badgeToRemove) {
                badgeToRemove.remove();
                }
            }
        };
    });

    document.getElementById('createTagButton').addEventListener('click', function(event) {
        event.preventDefault();
        const newTagName = document.getElementById('newTagName').value.trim();
        if (newTagName) {
            const addTagForm = document.getElementById('addTagForm');
            if (addTagForm) {
                document.getElementById('hiddenTagName').value = newTagName;
                addTagForm.submit();
            } else {
                console.error('Form addTagForm not found.');
            }
        }
    });

    document.addEventListener('DOMContentLoaded', function() {
        var successMessage = document.getElementById('success-message');
        if (successMessage) {
            setTimeout(function() {
                successMessage.style.display = 'none';
            }, 3000);
        }
    });
</script>
{% endblock %}

templates/notes_app/note_detail.html
{% extends 'base.html' %}

{% block title %}Деталі нотатки{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4 text-center card" style="color: #E2B29B;">{{ note.title }}</h1>
    
    <div class="card mb-4 p-3" style="background-color: #40886E; border-radius: 10px; color: #E2B29B;">
        <p>{{ note.content }}</p>
    </div>
    
    <p class="text-left" style="color: #E2B29B;">Time of creation: {{ note.created_at|date:"d.m.Y H:i" }}</p>
    <!-- <p class="text-center" style="color: #E2B29B;">{{ note.created_at|date:"d.m.Y H:i" }}</p> -->
    <div class="mb-4 d-flex flex-wrap justify-content">
        <p class="text-left" style="color: #E2B29B; margin-top: 6px;">Tags:</p>
        <div class="mb-2 d-flex flex-wrap justify-content" style="background-color: #3D6657; border-radius: 10px; padding: 10px;">
            {% for tag in note.tags.all %}
                <span class="badge" style="background-color: #6FBDA2; color: #155840; margin-left: 5px;">{{ tag.name }}</span>
            {% empty %}
                <span class="badge" style="background-color: #6FBDA2; color: #155840; margin: 5px;">Теги відсутні</span>
            {% endfor %}
        </div>
    </div>

    <div class="d-flex justify-content-between">
        <a href="{% url 'edit_note' note.id %}" class="btn btn-primary" style="flex: 1; margin-right: 10px; padding: 6px 12px; margin-top: 8px;">Edit note</button>
        <a href="{% url 'delete_note' note.id %}" class="btn" style="flex: 1; margin-right: 10px; padding: 6px 12px; margin-top: 8px; background-color: #a40c0c;" onclick="return confirm('Are you sure you want to delete this note?');">Delete</a>
        <a href="{% url 'note_list' %}" class="btn btn-block" style="flex: 1; background-color: #155840; color: #fff; padding: 6px 12px; margin-top: 8px;">Back to list</a>
    </div>
    
    
</div>
{% endblock %}

templates/notes_app/note_home.html
{% extends 'base.html' %}

{% block title %}Main Note Page{% endblock %}

{% block content %}
<div class="card contact-form-container" style="text-align: center;">
    <div class="card-header" style="background-color: #155840; color: #E2B29B; border-radius: 4px;">
        <h1 class="m-2">Manage notes</h1>
    </div>
    <div class="card-body">
        <div class="list-group">
            <a href="{% url 'add_note' %}" class="list-group-item list-group-item-action" style="background-color: #3D6657 !important; color: #E2B29B;">
                Add note
            </a>
            <a href="{% url 'note_list' %}" class="list-group-item list-group-item-action" style="background-color: #3D6657 !important; color: #E2B29B;">
                Note list
            </a>
        </div>
    </div>
</div>
{% endblock %}

templates/notes_app/note_list.html
{% extends 'base.html' %}

{% block title %}Note list{% endblock %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/notes_list.css' %}">

{% block content %}
    <div class="container">
        <h1 class="mb-4 text-center card" style="color: #E2B29B;">Note list</h1>

        <div class="card mb-4" style="background-color: #40886E; border-radius: 10px; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3);">
            <form method="GET" class="p-3">
                <input type="text" name="q" placeholder="Search by name or tag..." class="form-control form-control-search" value="{{ request.GET.q }}">
                <button type="submit" class="btn btn-search mt-2">Search</button>               
            </form>
            <a href="{% url 'add_note' %}" class="btn btn-search mt-2" style="width: 100%">Add note</a>
            <a href="{% url 'tag_list' %}" class="btn btn-search mt-2" style="width: 100%">Manage tags</a>

        </div>

        <div class="card" style="background-color: #40886E; border-radius: 10px; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3);">
            <ul class="list-group list-group-flush">
                {% for note in page_obj %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <a href="{% url 'note_detail' note.id %}" class="note-title">{{ note.title }}</a>
                        
                        <div>
                            <span class="note-date text-center" style="color: #E2B29B; font-size: 0.9em; white-space: nowrap; margin: 0 10px;">{{ note.created_at|date:"Y-m-d H:i" }}</span>
                            <a href="{% url 'edit_note' note.id %}" class="btn btn-warning btn-sm btn-custom">Edit 🖊</a>
                            <a href="{% url 'delete_note' note.id %}" class="btn btn-danger btn-sm btn-danger-custom" onclick="return confirm('Are you sure you want to delete this note?');">Delete 🗑</a>

                        </div>
                    </li>
                {% empty %}
                    <li class="list-group-item" style="background-color: #3D6657; color: #E2B29B;">No notes.</li>
                {% endfor %}
            </ul>
        </div>

        

        {% if page_obj.paginator.num_pages > 1 %}
            <div class="pagination mt-4">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; First</a>
                        <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">Next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
    </div>

    <script>
        function confirmDelete() {
            return confirm("Are you sure you want to delete this note?");
        }
    </script>

{% endblock %}