news_app/urls.py
from django.urls import path
from .views import ExchangeRateNewsView

urlpatterns = [
    path('news/', ExchangeRateNewsView.as_view(), name='exchange_rate_news'),
]

personal_assistant/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name='home'),
    path('home/', HomePageView.as_view(), name='home'),
    path('contacts/', include('contacts_app.urls')),
    path('notes/', include('notes_app.urls')),
    path('news/', include('news_app.urls')),
    path('users/', include('users_app.urls')),
    path('files/', include('files_app.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users_app/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', login_required(views.logoutuser), name='logout'),
    path('profile/', login_required(views.profile), name='profile'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Base{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'SudoTeam.ico' %}">
    <link rel="stylesheet" href="{% static 'pagination.css' %}">
    <link rel="stylesheet" href="{% static 'contacts_app/add_contact.css' %}">
    <link rel="stylesheet" href="{% static 'contacts_app/contacts_list.css' %}">
    <link rel="stylesheet" href="{% static 'files_app/files_app.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Moderustic:wght@300..800&display=swap" rel="stylesheet">
</head>
<body style="background-color: #3D6657; color: #E2B29B;">
    <nav class="navbar navbar-expand-lg" style="background-color: #155840; color: #E2B29B;">
        <a class="navbar-brand" href="{% url 'home' %}" style="color: #81BDA8;">Personal Assistant</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav" style="margin-top: 5px;">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}" style="color: #E2B29B;">Home</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'contact_list' %}" style="color: #E2B29B;">Contacts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'note_list' %}" style="color: #E2B29B;">Notes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'file_list' %}" style="color: #E2B29B;">Cloud storage</a>
                    </li>
                {% endif %}
            </ul>
            <span class="navbar-text ml-auto" style="color: #E2B29B;">
                {% if user.is_authenticated %}
                    Hello, <a href="{% url 'users:profile' %}" style="color: #81BDA8;">{{ user.username }}</a>!
                    <a href="{% url 'users:logout' %}" class="btn btn-danger" style="margin-left: 10px; background-color: #CA825F; border: none;">Logout</a>
                {% else %}
                    <a href="{% url 'users:login' %}" class="btn btn-primary" style="background-color: #6FBDA2; border: none;">Log In</a>
                    <a href="{% url 'users:signup' %}" class="btn btn-primary" style="background-color: #6FBDA2; border: none; margin-left: 10px;">Sign Up</a>
                {% endif %}
            </span>
        </div>
    </nav>
    
    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Your personal Assistant{% endblock %}

{% block content %}
<div class="container" style="padding-top: 20px;">
    <!-- <div class="row">
        <div class="col-12 text-end" style="position: relative;">
            <div class="position-absolute" style="right: 0; top: 0; z-index: 1000; color: #E2B29B;">
                <strong>Курси валют:</strong> 
                {% if error %}
                    <span class="text-danger">{{ error }}</span>
                {% else %}
                    <span>1 USD = {{ usd_to_uah }} UAH</span> | 
                    <span>1 EUR = {{ eur_to_uah }} UAH</span> | 
                    <span>1 PLN = {{ pln_to_uah }} UAH</span>
                {% endif %}
            </div>
        </div>
    </div> -->

    <h1 style="color: #81BDA8;">HOT NEWS</h1>

    {% for category, articles in news_by_category.items %}
        <h2 style="color: #6FBDA2; border-bottom: 2px solid #E2B29B; padding-bottom: 5px; margin-bottom: 10px;">
            <a href="#" class="category-toggle" data-target="#category-{{ forloop.counter }}" style="text-decoration: none; color: inherit;">{{ category|title }}</a>
        </h2>
        <div class="list-group mb-4 category-content" id="category-{{ forloop.counter }}" style="display: none;">
            {% for article in articles %}
                <div class="list-group-item" style="position: relative; padding-bottom: 40px; border: 2px solid rgba(0, 0, 0, 0.199);">
                    <h5 class="mb-1" style="color: #E2B29B;">{{ article.title }}</h5>
                    <p class="mb-1">{{ article.description }}</p>
                    <small class="text-muted">Author: {{ article.author }} | Date: {{ article.published_at }}</small>
                    <a href="{{ article.url }}" class="btn btn-outline-primary mt-2" style="display: block; margin-top: 10px; background-color: transparent !important; border: 2px solid #E2B29B !important; color: #E2B29B !important; text-decoration: none !important;">Read more</a>
                </div>
            {% empty %}
                <p>There are no available news for this category.</p>
            {% endfor %}
        </div>
    {% empty %}
        <p>No news available.</p>
    {% endfor %}

    <style>
        #scrollToTopBtn {
            background-color: #E2B29B;
            color: white;
            border: 2px solid transparent;
            transition: background-color 0.3s, border-color 0.3s;
        }

        #scrollToTopBtn:hover {
            background-color: transparent;
            border-color: #E2B29B;
            color: #E2B29B;
        }
    </style>

    <a id="scrollToTopBtn" class="btn btn-outline-secondary" style="display: none; position: fixed; bottom: 20px; right: 20px; z-index: 1000;">Вгору</a>
</div>

<script>
    document.querySelectorAll('.category-toggle').forEach(function(toggle) {
        toggle.addEventListener('click', function(event) {
            event.preventDefault();
            const targetId = toggle.getAttribute('data-target');
            const targetElement = document.querySelector(targetId);
            if (targetElement.style.display === 'none' || targetElement.style.display === '') {
                targetElement.style.display = 'block';
                setTimeout(() => {
                    targetElement.style.opacity = 1;
                }, 0);
            } else {
                targetElement.style.opacity = 0;
                targetElement.style.display = 'none';
            }
        });
    });

    window.addEventListener('scroll', function() {
        const scrollToTopBtn = document.getElementById('scrollToTopBtn');
        if (window.scrollY > 100) {
            scrollToTopBtn.style.display = 'block';
        } else {
            scrollToTopBtn.style.display = 'none';
        }
    });

    document.getElementById('scrollToTopBtn').addEventListener('click', function() {
        window.scrollTo({ top: 0, behavior: 'smooth' });
    });
</script>

{% endblock %}

templates/news.html
<!-- {% extends 'base.html' %}

{% block title %}Новини{% endblock %}

{% block content %}
    <div class="header-container">
        <h2>Останні новини</h2>
        <div class="exchange-rate">
            <h3>Популярні валютні курси</h3>
            {% if usd_to_uah and eur_to_uah and pln_to_uah %}
                <p>USD to UAH: {{ usd_to_uah }}</p>
                <p>EUR to UAH: {{ eur_to_uah }}</p>
                <p>PLN to UAH: {{ pln_to_uah }}</p>
            {% else %}
                <p>{{ error }}</p>
            {% endif %}
        </div>
    </div>

    <div class="news-container">
        {% for category, articles in news_by_category.items %}
            <div class="news-section">
                <button class="toggle-news" onclick="toggleNews('{{ category|slugify }}')">
                    {{ category|title }} News
                </button>
                <div class="news-list" id="{{ category|slugify }}">
                    {% if articles %}
                        <ul>
                            {% for article in articles %}
                                <li>
                                    <h4><a href="{{ article.url }}" target="_blank">{{ article.title }}</a></h4>
                                    <p>{{ article.description }}</p>
                                    <p><strong>Автор:</strong>
                                    {% if article.author and article.author != "None" %}
                                        {{ article.author }}
                                    {% else %}
                                        Невідомий
                                    {% endif %}
                                    </p>
                                    <p>{{ article.published_at }}</p>
                                </li>
                            {% endfor %}
                        </ul>
                        <div class="back-to-top">
                            <button onclick="scrollToTop()" class="button">Повернутися на верх сторінки</button>
                        </div>
                    {% else %}
                        <p>Не знайдено новин на цю категорію.</p>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>

    <style>
        .header-container {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .exchange-rate {
            text-align: right;
        }

        .news-list {
            display: none;
            margin-top: 10px;
            background-color: #f9f9f9;
            border: 1px solid #ccc;
            border-radius: 8px;
            padding: 10px;
        }

        .toggle-news {
            display: block;
            width: 100%;
            padding: 10px;
            background-color: #007bff; 
            color: white; 
            border: none;
            cursor: pointer;
            text-align: left;
            margin: 5px 0;
            border-radius: 5px;
        }

        .toggle-news:hover {
            background-color: #0056b3; 
        }

        ul {
            padding-left: 20px;
        }

        li {
            margin-bottom: 15px;
            background-color: #ffffff; 
            border-radius: 5px; 
            padding: 10px; 
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }

        .back-to-top {
            text-align: center;
            margin-top: 20px;
        }

        .button {
            padding: 10px 20px; 
            background-color: #007bff; 
            color: white; 
            border: none; 
            border-radius: 5px;
            cursor: pointer; 
            transition: background-color 0.3s; 
        }

        .button:hover {
            background-color: #0056b3; 
        }
    </style>

    <script>
        function toggleNews(category) {
            const newsList = document.getElementById(category);
            const backToTopButton = newsList.querySelector('.back-to-top');

            if (newsList.style.display === "block") {
                newsList.style.display = "none";
                backToTopButton.style.display = "none"; 
            } else {
                newsList.style.display = "block";
                backToTopButton.style.display = "block"; 
            }
        }

        function scrollToTop() {
            window.scrollTo({
                top: 0,
                behavior: 'smooth' 
            });
        }
    </script>
{% endblock %} -->