news_app/urls.py
from django.urls import path
from .views import ExchangeRateNewsView

urlpatterns = [
    path('news/', ExchangeRateNewsView.as_view(), name='exchange_rate_news'),
]

personal_assistant/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name='home'),
    path('home/', HomePageView.as_view(), name='home'),
    path('contacts/', include('contacts_app.urls')),
    path('notes/', include('notes_app.urls')),
    path('news/', include('news_app.urls')),
    path('users/', include('users_app.urls')),
    path('files/', include('files_app.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users_app/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', login_required(views.logoutuser), name='logout'),
    path('profile/', login_required(views.profile), name='profile'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

users_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from .models import Profile


class RegisterForm(UserCreationForm):
    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'username',
        })
    )

    email = forms.EmailField(
        max_length=100,
        required=True,
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'email',
        })
    )

    password1 = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'password',
        })
    )

    password2 = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'password confirmation',
        })
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        labels = {
            'username': 'Username',
            'email': 'Email Address',
            'password1': 'Password',
            'password2': 'Password confirmation',
        }

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(
            *args, **kwargs)
        for field, label in self.Meta.labels.items():
            self.fields[field].label = label


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'username',
        })
    )

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'password',
        })
    )

    class Meta:
        model = User
        fields = ['username', 'password']
        labels = {
            'username': 'Username',
            'password': 'Password',
        }

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for field, label in self.Meta.labels.items():
            self.fields[field].label = label


class ProfileForm(forms.ModelForm):
    avatar = forms.ImageField(
        required=False,
        widget=forms.ClearableFileInput(attrs={
            'class': 'form-control-file',
        })
    )

    class Meta:
        model = Profile
        fields = ['avatar']
        labels = {
            'avatar': 'Avatar',
        }
        

templates/users/login.html
{% extends 'base.html' %}

{% load static %}
{% load custom_filters %}

{% block title %}Authentication{% endblock %}

{% block content %}
<div class="card" style="background-color: #3D6657; color: #E2B29B;">
    <div class="card-header" style="background-color: #155840; color: #E2B29B; border-radius: 5px;">
        <h2 class="text-center">Authentication</h2>
    </div>
    <div class="card-body">
        {% if messages %}
            <div class="alert alert-danger" role="alert" style="background-color: #D9534F !important; color: #662826;">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}

        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                {{ form.username.label_tag }}
                {{ form.username|add_class:"form-control" }}
                {{ form.username.errors|striptags }}
            </div>
            <div class="form-group">
                {{ form.password.label_tag }}
                {{ form.password|add_class:"form-control" }}
                {{ form.password.errors|striptags }}
            </div>
            <div class="form-group d-flex justify-content-between">
                <button type="submit" class="btn btn-primary" style="background-color: #6FBDA2; border: none;">Login</button>
                <p style="margin: 0; margin-top: 15px; align-self: center;">Forgot Password? <a href="{% url 'users:password_reset' %}" style="color: #E2B29B;">Reset your password</a></p>
            </div>
            <div class="form-group text-center">
                <p>Don't have an account? <a href="{% url 'users:signup' %}" style="color: #E2B29B;">Sign Up</a></p>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/users/password_reset.html
{% extends 'base.html' %}

{% block title %}Password reset{% endblock %}

{% load static %}
{% load custom_filters %}

{% block content %}
<div class="card" style="background-color: #3D6657; color: #E2B29B;">
    <div class="card-header" style="background-color: #155840; color: #E2B29B; border-radius: 5px;">
        <h2 class="text-center">Reset your password</h2>
    </div>
    <div class="card-body">
        {% if messages %}
            <div class="alert alert-danger" role="alert" style="background-color: #D9534F !important; color: #662826;">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}
        
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_email" style="color: #E2B29B;">Your Email Address:</label>
                {{ form.email|add_class:"form-control" }}

                {% if form.email.errors %}
                    <div class="alert alert-danger" role="alert" style="background-color: #D9534F !important; color: #662826;">
                        {% for error in form.email.errors %}
                            {{ error|striptags }}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary" style="background-color: #6FBDA2; border: none;">Reset Password</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/users/password_reset_complete.html
{% extends "base.html" %}

{% block content %}
<div class="card" style="background-color: #3D6657; color: #E2B29B;">
    <div class="card-header" style="background-color: #155840; color: #E2B29B;">
        <h2 class="text-center">Password changed successfully</h2>
    </div>
    <div class="card-body text-center">
        <p>Your password has been successfully updated.</p>
        <a href="{% url 'users:login' %}" class="btn btn-primary" style="background-color: #6FBDA2; border: none;">Log In</a>
    </div>
</div>
{% endblock %}

templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block title %}Password Reset{% endblock %}

{% block content %}
<div class="card" style="background-color: #3D6657; color: #E2B29B;">
    <div class="card-header" style="background-color: #155840; color: #E2B29B;">
        <h2 class="text-center">Change Your Password Here</h2>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="form-group">
                <label for="{{ form.new_password1.id_for_label }}" style="color: #E2B29B;">New password:</label>
                <div>{{ form.new_password1 }}</div>
                {% if form.new_password1.errors %}
                    <div class="alert alert-danger" role="alert" style="background-color: #D9534F !important; color: #662826; border-color: #75262385;">
                        {{ form.new_password1.errors|striptags  }}
                    </div>
                {% endif %}
        </div>
            <div class="form-group">
                <label for="{{ form.new_password2.id_for_label }}" style="color: #E2B29B;">Confirmation password:</label>
                <div>{{ form.new_password2 }}</div>
                {% if form.new_password2.errors %}
                    <div class="alert alert-danger" role="alert" style="background-color: #D9534F !important; color: #662826; border-color: #75262385;">
                        {{ form.new_password2.errors|striptags  }}
                    </div>
                {% endif %}            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary" style="background-color: #6FBDA2; border: none;">Save new password</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/users/password_reset_done.html
{% extends 'base.html' %}

{% block title %}Password Reset{% endblock %}

{% block content %}
<div class="card" style="background-color: #3D6657; color: #E2B29B;">
    <div class="card-header" style="background-color: #155840; color: #E2B29B; border-radius: 5px;">
        <h2 class="text-center">Password Reset</h2>
    </div>
    <div class="card-body text-center">
        <p>We have sent instructions for resetting the password to your email.</p>
        <p>Please check your email.</p>
    </div>
</div>
{% endblock %}

templates/users/password_reset_email.html
{% autoescape off %}
Hello {{ user.get_username }},

You have sent a password reset request for your account on {{ domain }}. To reset your password, follow the link below:

<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>

If you did not make this request, simply ignore this message.

With best wishes,
{{ domain }} command
{% endautoescape %}

templates/users/profile.html
{% extends 'base.html' %}

{% load static %}
{% load custom_filters %}

{% block title %}Profile{% endblock %}

{% block content %}
<div class="card" style="background-color: #3D6657; color: #E2B29B;">
    <div class="card-header" style="background-color: #155840; color: #E2B29B;">
        <h2 class="text-center">Your profile</h2>
    </div>
    <div class="card-body">
        <div class="form-group text-center">
            <img src="{{ user.profile.avatar|default:'https://sudoteam.s3.eu-north-1.amazonaws.com/default_avatar.png' }}" class="rounded-circle" alt="Avatar" style="width: 150px; height: 150px;">
        </div>

        <div class="form-group">
            <label for="username">Username:</label>
            <input type="text" id="username" value="{{ user.username }}" class="form-control" readonly>
        </div>

        <div class="form-group">
            <label for="email">Email Address:</label>
            <input type="email" id="email" value="{{ user.email }}" class="form-control" readonly>
        </div>
    </div>
</div>
{% endblock %}

templates/users/signup.html
{% extends 'base.html' %}

{% load static %}
{% load custom_filters %}

{% block title %}Create your account{% endblock %}

{% block content %}
<div class="card" style="background-color: #3D6657; color: #E2B29B;">
    <div class="card-header" style="background-color: #155840; color: #E2B29B;">
        <h2 class="text-center">Create your account</h2>
    </div>
    <div class="card-body">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                {{ form.username.label_tag }}
                {{ form.username|add_class:"form-control" }}
                {% if form.username.errors %}
                    <div class="alert alert-danger" role="alert" style="background-color: #D9534F !important; color: #662826; border-color: #75262385;">
                        {{ form.username.errors|striptags  }}
                    </div>
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.email.label_tag }}
                {{ form.email|add_class:"form-control" }}
                {% if form.email.errors %}
                    <div class="alert alert-danger" role="alert" style="background-color: #D9534F !important; color: #662826; border-color: #75262385;">
                        {{ form.email.errors|striptags }}
                    </div>
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.password1.label_tag }}
                {{ form.password1|add_class:"form-control" }}
                {% if form.password1.errors %}
                    {% for error in form.password1.errors %}
                        <div class="alert alert-danger" role="alert" style="background-color: #D9534F !important; color: #662826; border-color: #75262385;">
                            {{ error|striptags }}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            
            <div class="form-group">
                {{ form.password2.label_tag }}
                {{ form.password2|add_class:"form-control" }}
                {% if form.password2.errors %}
                    {% for error in form.password2.errors %}
                        <div class="alert alert-danger" role="alert" style="background-color: #D9534F !important; color: #662826; border-color: #75262385;">
                            {{ error|striptags }}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            
            <div class="form-group">
                <button type="submit" class="btn btn-primary" style="background-color: #6FBDA2; border: none;">Sign up</button>
            </div>
            <div class="form-group text-center">
                <p>Have an account? <a href="{% url 'users:login' %}" style="color: #E2B29B;">Log in now</a></p>
            </div>
        </form>
    </div>
</div>
{% endblock %}